name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release-linux:
    name: Release Linux
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-4-dev libgdk-pixbuf2.0-dev libpango1.0-dev libcairo2-dev libglib2.0-dev libwebkit2gtk-4.1-dev libadwaita-1-dev libsecret-1-dev libsqlite3-dev libssl-dev pkg-config
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Build release
      run: cargo build --release --verbose --workspace
    
    - name: Create AppImage
      run: |
        # This would require additional setup for AppImage creation
        echo "AppImage creation would go here"
    
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.upload_url }}
        asset_path: target/release/asgard-mail
        asset_name: asgard-mail-linux
        asset_content_type: application/octet-stream

  release-windows:
    name: Release Windows
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install MSYS2 and GTK dependencies
      run: |
        # Install MSYS2
        choco install msys2 -y
        
        # Add MSYS2 to PATH
        $env:PATH = "C:\msys64\mingw64\bin;C:\msys64\usr\bin;$env:PATH"
        
        # Install GTK development libraries
        C:\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm mingw-w64-x86_64-gtk4 mingw-w64-x86_64-glib2 mingw-w64-x86_64-pkg-config mingw-w64-x86_64-cairo mingw-w64-x86_64-pango mingw-w64-x86_64-gdk-pixbuf2 mingw-w64-x86_64-libadwaita mingw-w64-x86_64-libsecret mingw-w64-x86_64-sqlite3 mingw-w64-x86_64-openssl"
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Build release
      run: cargo build --release --verbose --workspace
      env:
        # Windows-specific environment variables for GTK
        PKG_CONFIG_PATH: "C:\msys64\mingw64\lib\pkgconfig"
        PATH: "C:\msys64\mingw64\bin;C:\msys64\usr\bin;$env:PATH"
    
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.upload_url }}
        asset_path: target/release/asgard-mail.exe
        asset_name: asgard-mail-windows.exe
        asset_content_type: application/octet-stream

  release-macos:
    name: Release macOS
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        brew install gtk4 gdk-pixbuf pango cairo glib webkitgtk libadwaita libsecret sqlite openssl pkg-config
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Build release
      run: cargo build --release --verbose --workspace
    
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.upload_url }}
        asset_path: target/release/asgard-mail
        asset_name: asgard-mail-macos
        asset_content_type: application/octet-stream
